version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/PHANIKUMARGV/demo-repo2"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "google-java-format"